{% set name = "gb-io" %}
{% set version = "0.3.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir --use-pep517
  run_exports:
    - {{ pin_subpackage('gb-io', max_pin="x.x") }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gb_io-{{ version }}.tar.gz
  sha256: 8e7a959ebcbffda8d898c3fa6c6517c3957dac4b373c6edf1e058eefb756edde

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools-rust
  run:
    - python

test:
  imports:
    - gb_io

about:
  home: https://github.com/althonos/gb-io.py
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A Python interface to gb-io, a fast GenBank parser and serializer written in Rust.
  dev_url: https://github.com/althonos/gb-io.py

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
