{% set name = "CHAMOIS" %}
{% set name_pypi = "chamois-tool" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/c/{{ name_pypi }}/{{ name_pypi | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d46c70942bcdc3bf97f19629700be29a7dd9613d18ebd2b09d737861567cd889

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  run_exports:
    - {{ pin_subpackage("chamois", max_pin="x.x") }}

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=39.2
    - wheel >=0.30
    - pyhmmer >=0.8
    - rich >=12.4.0
  run:
    - python >=3.7
    - importlib_resources >=1.0  #[py37, py38, py39]
    - numpy >=1.16
    - anndata >=0.8
    - gb-io >=0.3.1
    - lz4 >=4.0
    - numpy >=1.0
    - pandas >=1.3
    - platformdirs >=3.0
    - pyhmmer >=0.11.0
    - pyrodigal >=3.0
    - rich >=12.4.0
    - rich-argparse >=1.1
    - scipy >=1.4
    - scikit-learn >=1.0
    - kennard-stone >=2.1
    - rdkit >=2023.3

test:
  imports:
    - {{ name|lower }}
  commands:
    - python -m {{ name|lower }} --help

about:
  home: https://chamois.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Chemical Hierarchy Approximation for secondary Metabolism clusters Obtained In Silico.

extra:
  recipe-maintainers:
    - althonos
  identifiers:
    - doi:10.1101/2025.03.13.642868  # bioRxiv preprint
